name: Docker Build and Push

on:
  push:
    branches:
      - main  # 触发构建的分支
  pull_request:
    branches:
      - main  # 提交 PR 时也会触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker 环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 获取最新的 Git 标签
      - name: Get latest Git tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)  # 获取最新标签
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vscode-server:${{ env.LATEST_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/vscode-server:${{ env.LATEST_TAG }} ${{ secrets.DOCKER_USERNAME }}/vscode-server:latest

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/vscode-server:${{ env.LATEST_TAG }}
           docker push ${{ secrets.DOCKER_USERNAME }}/vscode-server:latest
